spring:
  application:
    name: restFulApiService
  datasource:
    url: jdbc:mysql://localhost:3306/restfulapi?serverTimezone=UTC&characterEncoding=UTF-8
    username: restful
    passㅁㄴword: rest123
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org.springframework: info

server:
  port: 8088